return {
  cmd = {
    "clangd",
    "--enable-config",
    "--all-scopes-completion",
    "--background-index",
    "--clang-tidy",
    "--clang-tidy-checks=*",
    "--compile-commands-dir=build",
    "--completion-style=detailed",
    "--cross-file-rename",
    "--experimental-modules-support",
    "--fallback-style=google",
    "--function-arg-placeholders",
    "--header-insertion-decorators",
    "--header-insertion=iwyu",
    "--pch-storage=memory",
    "--query-driver=/usr/bin/**/clang-*,/usr/local/bin/clang*,/bin/clang,/bin/clang++,/usr/bin/gcc,/usr/bin/g++",
    "-j=12",
  },
  filetypes = { "c", "cpp" },
  root_markers = {
    ".clangd",
    ".clang-tidy",
    ".clang-format",
    "compile_commands.json",
    "compile_flags.txt",
    "configure.ac",
    "aconfigure.ac",
    "CMakeLists.txt",
    "Makefile",
  },
  capabilities = {
    textDocument = {
      completion = {
        editsNearCursor = true,
      },
    },
    offsetEncoding = { "utf-8", "utf-16" },
  },
  init_options = {
    usePlaceholders = true,
    completeUnimported = true,
    clangdFileStatus = true,
  },
}
